### ISSUE TITLE
`sudo sgdisk $INSPARTITION --attributes=2:set` gives "Could not convert bit number" error

### ISSUE THREAD

**Issue by archived-aft-bogus-german-visa-rejectio** [fdiblen/Arch-Linux-Dell-XPS13-9350#1]
Hi there I'm an Arch Linux noob (aka script kiddo) trying out your script. And this line seemed strange and it gave weird error:`Could not convert bit number` as it tries `Creating new GPT entires`.  

I guess there is a typo here.

So I went to read up on `sgdisk` but couldnt figure out the typo.

So I did `sgdisk -A 3:set:2 $INSDRIVE ` and it kinda did the same thing too I guess.

**Comment by fdiblen** [comment]
Hi,
This command make the partition bootable. In principle, you can use any distlk editor such as cfdisk or fdisk.
If you could send me the details of your setup, I could have a look. Just keep in mind that these instructions are for a fresh installation.

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Hi thanks for the quick response. 

I'm installing afresh here. Yeah I achieved the same result with `sgdisk -A 3:set:2 $INSDRIVE`

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Please correct the typo and make sure it is a valid command. thank you.

**Comment by fdiblen** [comment]
fixed by 80bb767dd1c2ec4949c14f4ad2699d57ce67d3a5

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
Cheers!
