### ISSUE TITLE
Grub-install: error: disk 'crpytouuid/<uuid>' not found

### ISSUE THREAD

**Issue by archived-aft-bogus-german-visa-rejectio** [fdiblen/Arch-Linux-Dell-XPS13-9350#2]
Hi there.

I followed the instructions and currently at the Grub installation stage. 
I ran `grub-install --target=i386-pc $INSDRIVE` and got the following error:

```
Grub-install: error: disk 'crpytouuid/0cebxxxxxxxxxxx' not found
```

I went to check my `/dev/disk/by-uuid` and saw that `0cebxxxxxxxxxxx` is indeed the uuid of my third partition `nvme0n1p3`.

So I did `grub-install --target=i386-pc $INSDRIVE --verbose` and this is what I get:

![img_3815](https://user-images.githubusercontent.com/10269911/39839103-af55e006-540d-11e8-8f33-f59e6b68f642.JPG)

As you can see in the screenshot `grub-install` logs that 

`/dev/mapper/cryptroot is not present.`

so that can be where the problem is.

Though doing `ls /dev/mapper/cryptroot` shows that `/dev/mapper/cryptroot` exists.

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
https://unix.stackexchange.com/questions/442877/grub-install-error-disk-crpytouuid-uuid-not-found

**Comment by fdiblen** [comment]
The new guide uses systemd boot.
See https://github.com/fdiblen/ultimate-arch/blob/master/X1E.md
